Fix for linux
tintin10q/minecraft-logs-analyzer pull request #3
Opened 2022-09-29 17:22 UTC by othello777

There were several errors keeping me from running the script on my Linux Mint 21 machine. I am not the most experienced in python but these fixes should allow it to run on linux without affecting anyone else's experience. Then again, it could just be my install that had these issues.

The icon didn't want to import
```py
Traceback (most recent call last):
  File ".../minecraft-logs-analyzer/minecraft_logs_analyzer.pyw", line 478, in <module>
    root.iconbitmap("icon.ico")
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "icon.ico" not defined
```
so I had it not use the icon on linux.

The second error happened when I ran it.
```py
Traceback (most recent call last):
  File ".../minecraft-logs-analyzer/minecraft_logs_analyzer.pyw", line 263, in count_playtimes_tread
    total_time += count_playtime(path, print_files='full' if len(paths) > 1 else 'file')
  File ".../minecraft-logs-analyzer/minecraft_logs_analyzer.pyw", line 144, in count_playtime
    for log in iter_logs(path):
  File ".../minecraft-logs-analyzer/minecraft_logs_analyzer.pyw", line 132, in iter_logs
    with open_methods[file.suffix](file, 'rt', encoding='ansi', errors='replace', newline='') as f:
  File "/usr/lib/python3.10/gzip.py", line 66, in open
    return io.TextIOWrapper(binary_file, encoding, errors, newline)
LookupError: unknown encoding: ansi
```
It seems that ansi isn't actually supported in python (or so I heard) so I changed it to UTF-8 which made it work perfectly.

And then I added a bit of info in the README to tell linux users they could run it as seeing the exe might turn them away.
Feel free to take/leave/revert any of these changes.

2022-10-10 23:58 UTC, tintin10q commented
Thanks for this!!

2022-10-11 00:13 UTC, tintin10q commented
I get the same issue with the `.ico` file. However, I think it is better to just put a try .. except around it instead with the `tkinter.TclError`. Instead of just blocking loading the ico file on all linux.

2022-10-11 00:13 UTC, tintin10q requested changes
I get the same issue with the `.ico` file. However, I think it is better to just put a try .. except around it instead with the `tkinter.TclError`. Instead of just blocking loading the ico file on all linux.

2022-10-11 00:17 UTC, tintin10q requested changes
However with the text encoding you should check the platform. Because I do think it is actually ansi on windows. So please change the platform check at the ico to a try ... except, with just the same couldn't load icon print at the except, 

(I edited this in after I made the next comment) and this code in the try:
```python
if os.path.exists("icon.ico"):
         img = PhotoImage(file='splash.png')
         root.tk.call('wm', 'iconphoto', root._w, img)
```

Also make sure to add PhotoImage to the list of tkinter imports. This is great because now you can have the icon on linux as well!

And please add a platform check with the encoding. Unless utf-8 is also compatible with ansi? I don't know.

2022-10-11 00:27 UTC, tintin10q commented
Actually, I dug around a bit and found this [stack overflow](https://stackoverflow.com/questions/11176638/tkinter-tclerror-error-reading-bitmap-file). 

This works but not with the .ico file. I also tried to open the .ico file and it looks very weird on linux. So instead of using the .ico file (on linux I guess) we can just use the `splash.png` as the icon. Which you can do with this code:

```python
if os.path.exists("icon.ico"):
         img = PhotoImage(file='splash.png')
         root.tk.call('wm', 'iconphoto', root._w, img)
```

Also make sure to add `PhotoImage` to the list of tkinter imports. This is great because now you can have the icon on linux as well!

![Splash](splash.png)

2022-10-12 03:57 UTC, othello777 commented
Sorry for taking so long to respond. Awesome! I don't have much python experience but I will try to add these changes a little better.

> Unless utf-8 is also compatible with ansi?  

Potentially, it just seemed to instantly work for me. I could do the platform check for linux, but I'd think people running on windows with base python would run into the same problem. I did test it on an old partition of mine which was NTFS from windows 10 if that matters at all.

Gimme a sec to add the stuff

2022-10-12 23:57 UTC, tintin10q commented
> Potentially, it just seemed to instantly work for me. I could do the platform check for linux, but I'd think people running on windows with base python would run into the same problem.

Ok I looked into it for me on linux ansi also generates an error. So I think it is better to instead of the platform check to also just wrap the code that opens with ansi encoding with a try ... except and then just try again with utf-8 if ansi does not work. The exception that it generates `LookupError`, (unknown encoding: ansi). So just except a LookupError and then try again with utf-8 instead of the platform check.

2023-11-09 01:37 UTC, merged